#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Spark (aka pxscene) Appvoyer configuration file
#
#   Author: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>
#

version: 0dev.{build}

clone_depth: 50

platform: x86

image: Visual Studio 2017

environment:
  S: "c:/dw/pxCore"
  

clone_folder: "c:/dw/pxCore"

# Build pipeline: https://www.appveyor.com/docs/build-configuration/
init:
  - echo environment setup...
  - set
  - git config --system core.longpaths true
  - ps: "ls \"C:/\""

before_build:
  - cd %S%
  - call ci/appveyor-custodian.bat

build_script:
  - echo build_script...
  - cd %S%
  - call ci/build_win32.bat

test: off

cache:		
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/WinSparkle.dll 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/WinSparkle.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/WinSparkle_expat.lib  
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/glew32s.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/libjpeg.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/libpng16.lib    
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/pthreadVC2.dll 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/pthreadVC2.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/zlib.bsc
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/WinSparkle.exp
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/WinSparkle.pdb 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/WinSparkle_wx.lib  
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/freetype253MT_D.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/libcurld.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/libpng16.bsc 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/libturbojpeg.lib 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/pthreadVC2.exp 
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/pthreadVC2.pdb
    - c:/dw/pxCore/examples/pxScene2d/external/vc.build/builds/zlib.lib
# validator: https://ci.appveyor.com/tools/validate-yaml
